[http]
port 		= "8080"
staticRoot 	= "./static"

# filesystem
[fs]
temp = "/tmp"
staticRoot = "./static"

[aws]
accessKeyId 	= ""
secretAccessKey = ""

[aws.s3]
bucket 	= "img-api"

[cdn]
url = "http://img.tinyfactory.io/img"